### ISSUE TITLE
megasync crashes when trying to select local folder for sync

### ISSUE THREAD

**Issue by CapSel** [samuelbernardo/ssnb-overlay#11]
some time ago I encountered this problem in ArchLinux and "they" helped me solve:
```
We have seen some bug related with QT 5.10, that could be the cause of that. 
Please, either use the official package from https://mega.nz/sync

or try to recompile removing this line of code in src/MEGASync/MegaApplication.cpp:

   QApplication::setDesktopSettingsAware(false);
If that does not solve it, please, contact us again
```

My QT version is 5.9.6 but symptoms are same.
Could you add this "patch" to repo?

**Comment by samuelbernardo** [comment]
Hi,
I've version 3.6.6 installed and I can't reproduce that error.
I'm also using qt 5.9.6 with profile default 17.0 with some keyword unmasked packages.
Can you tell me the steps to reproduce the bug?
Thanks

**Comment by CapSel** [comment]
After opening Settings:
- select "Syncs" tab
- click "Add"
- click icon on the right side of "Local folder" (monitor icon?)

usually at this point megasync crashes for me.

I've recently reinstalled system and my home directory was clean. Recompilation with patch that I made base on email from Mega eliminates the crash.

I'm using gnome without systemd - dantrell profile for gnome 3.28 but I had the same crash on ArchLinux (yes - archlinux failed me for the last time ;)

**Comment by samuelbernardo** [comment]
I did the steps you mentioned and I couldn't reproduce that issue.
I'm also using kde with systemd, but the init systems should not be the source of the problem. Maybe the problem is with gnome desktop integration.
So I propose the following:
- create megasync-3.6.6-r1.ebuild with the patch you mentioned
- create new use flag gnome that will apply the necessary patch for gnome desktop

Thanks for your feedback.

**Comment by CapSel** [comment]
Sounds good. Thank you.

**Comment by samuelbernardo** [comment]
Finished push to overlay with the previous commit.
